# Generated by Django 4.2.4 on 2023-12-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_dish_price_currency_alter_dish_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
